### ISSUE TITLE
Questions about CodeRunnerRequestHandler ...

### ISSUE THREAD

**Issue by TomNussbaumer** [ruediste/remote-junit#1]
In the default constructor there is the following line:

``` java
        this(Executors.newCachedThreadPool()::execute);
```
1. Is it really a good idea to use a CachedThreadPool?
2. I have never seen a C++ like "::" in Java code. Is this something new addition to the language i have missed? What does it do?

**Comment by TomNussbaumer** [comment]
Don't mind the second question. I introduced myself to the latest Java8 stuff :)

**Comment by ruediste** [comment]
The `ServerCode` has to be executed asynchronously, such that the client immediately receives the session id and can start sending requests to it. For this purpose, a CachedThreadPool seemed appropriate. What are your objections?

**Comment by ruediste** [comment]
FYI: I worked on the Readme and the Javadocs during the last days. Check it out. More to come
